owner: CT-crew
repo: mw-monitoring

sites:
  - name: MW-HomePage
    url: https://millennialsworks.com
    icon: https://millennialsworks.com/favicon.ico
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    maxResponseTime: 5000
  - name: Ammw landing page
    url: https://info.ammw.net
    icon: https://info.ammw.net/favicon.ico
    maxResponseTime: 5000
  - name: SpaceV landing page
    url: https://spacev.info
    icon: https://spacev.info/images/favicon.png
    maxResponseTime: 5000
  - name: Mw-Admin
    url: $ADMIN_URL
    maxResponseTime: 5000
  - name: MW-Server
    method: GET
    url: $SERVER_URL
    headers:
      - "User-Agent: $CUSTOM_USER_AGENT"
    maxResponseTime: 5000
  - name: MUSIC
    url: $MUSIC_URL
    maxResponseTime: 5000
  - name: Google
    url: https://www.google.com
  - name: Cloudflare
    url: https://www.cloudflare.com/ko-kr
  - name: Docker
    url: https://www.docker.com
  - name: Figma
    url: https://www.figma.com

skipDeleteIssues: true

assignees:
  - KoJaem
  - shinbc89

status-website:
  baseUrl: /mw-monitoring
  name: mw-monitoring
  introTitle: "**MillennialsWorks** 모니터링 페이지입니다."
  introMessage: 현재 페이지에서 전반적인 서비스의 상태를 확인하실 수 있습니다.
  navbar:
    - title: Status
      href: /mw-monitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
