owner: CT-crew
repo: mw-monitoring

sites:
  - name: MW-HomePage
    url: http://millennialsworks.com
    icon: https://millennialsworks.com/favicon.ico
  - name: Ammw landing page
    url: https://info.ammw.net
    icon: https://info.ammw.net/favicon.ico
  - name: SpaceV landing page
    url: https://spacev.info
    icon: https://spacev.info/images/favicon.png
  - name: Mw-Admin
    url: $ADMIN_URL
  - name: MW-Server
    url: $SERVER_URL
    headers:
      - "User-Agent: $USER_AGENT"

skipDeleteIssues: true

assignees:
  - KoJaem

status-website:
  baseUrl: /mw-monitoring
  name: mw-monitoring
  introTitle: "**MillennialsWorks** 모니터링 페이지입니다."
  introMessage: 현재 페이지에서 전반적인 서비스의 상태를 확인하실 수 있습니다.
  navbar:
    - title: Status
      href: /mw-monitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
